---

- host: all
  become: true
  task:

  - name: update and upgrade the servers
    apt:
      upgarde_cache: yes
      upgrade: yes
      
  - name: set time to Africa/Lagos
    tags: time
    timezone: name=Africa/Lagos

  - name: install apache2
    tags: apache
    apt:
      name:
        - apache2
      state: latest

  - name: remove index.html
  file:
    path: /var/www/html/index.html
    state: absent

  - name: use the printf script
    shell:
     sudo echo "<h1>This is my hostname:</h1>" >> /var/www/html/index.html          
     sudo echo "<p>$(hostname -f)</p>" >> /var/www/html/index.html
    notify: restart apache

  handlers:
    - name: restart Apache
      tags: restart
      service:
        name: apache2
        state: restarted             